server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://192.168.1.11:3306/cloud?useUnicode=true&charaterEncoding=utf-8&useSSL=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhang.springcloud.entities

eureka:
  client:
    #表示向Server注册自己，默认为true
    register-with-eureka: true
    #是否从Server抓取已有的注册信息，默认为true，集群必须设置为true，才能配合Ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  #eureka web页面完善,去除主机名
  instance:
    instance-id: payment8001
    prefer-ip-address: true  #鼠标悬停显示ip地址

    #Eureka 客户端向服务器发送心跳的时间
    #lease-renewal-interval-in-seconds: 1
    #Eureka 服务器在收到最后一次心跳后等待时间上限
    #lease-expiration-duration-in-seconds: 2